version: '3'
services:
  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  server_a:
    build: .
    depends_on:
      - zipkin
    restart: on-failure
    environment:
      PORT: 8081
      TEMPERATURE_URI: http://172.17.0.1:8080
      NAME: server_a
      ZIPKIN_URL: http://zipkin:9411/api/v2/spans
    ports:
      - "8081:8081"

  server_b:
    build: .
    depends_on:
      - zipkin
    restart: on-failure
    environment:
      PORT: 8080
      TEMPERATURE_URI: http://172.17.0.1:8081
      NAME: server_b
      ZIPKIN_URL: http://zipkin:9411/api/v2/spans
    ports:
      - "8080:8080"